### ISSUE TITLE
test.html: Output and error always shown at player 0

### ISSUE THREAD

**Issue by eulerscheZahl** [CodinGame/codingame-game-engine#24] opened 2019-11-23 17:46 UTC
Regarding the local test page http://localhost:8888/test.html:
on turn-based games (with only a single player getting executed each turn), the SDK always shows the output and error stream at the first player. This bug was introduced somewhere between v3.6 and v3.7, it's working properly on the older version.

**Comment by Milkweedz** [comment] 2019-11-26 17:01
Hello, we were unable to reproduce the bug. Can you show us in detail how you were able to get it to happen?

**Comment by eulerscheZahl** [comment] 2019-11-26 17:09
Hello, this is the project causing problems for me: [Onitama](https://github.com/eulerscheZahl/Onitama).
Works fine with SDK version 3.6 but not with the latest one.
An online version is [here](https://www.codingame.com/ide/demo/8321711646300b37b8d4a7d3a279894ff59b69), it's playing fine on the website.

![image](https://user-images.githubusercontent.com/9901571/69655899-d0e45900-1077-11ea-9461-df3eb01d0b8c.png)
![image](https://user-images.githubusercontent.com/9901571/69655910-d346b300-1077-11ea-8cb2-b666e1faa477.png)

**Comment by Milkweedz** [comment] 2019-11-29 14:29
The client code wasn't handling the players' output correctly. It has been fixed in the latest release.

**Comment by CGjupoulton** [comment] 2019-11-29 15:48
Fixed in [v3.10.0](https://github.com/CodinGame/codingame-game-engine/tree/v3.10.0)

**Closed** 2019-11-29 15:49 UTC

**Comment by eulerscheZahl** [comment] 2019-11-29 19:12
Thanks, much better indeed.
But now [this line](https://github.com/CodinGame/codingame-game-engine/blob/master/runner/src/main/resources/view/app.js#L152) is spamming my console :stuck_out_tongue:
